---
slurm_packages:
  - slurmd
  - pmi

slurm_role: compute

install_packages: []

mpi_packages:
  oracle:
    - mpich
    - openmpi
  google:
    - mpich
    - openmpi
  aws:
    - mpich
    - openmpi

ceph_packages:
  - ceph
  - ceph-base
  - ceph-common
  - ceph-osd
  - ceph-mon
  - ceph-mgr
  - ceph-mds
  - ceph-radosgw
  - ceph-volume
  - lvm2

ceph_version: quincy

monitoring_role: client

ldap_hostname: "{{ ansible_local.citc.ldap_hostname }}"
