---

- hosts: compute
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
  become: yes
  tasks:
    - name: disable SELinux
      selinux:
        state: permissive
        policy: targeted
  roles:
    - citc_user
    - filesystem
    - ssh
    #- security_updates
    - ntp
    - sssd
    - lmod
    - packages
    - mpi
    - slurm
    - monitoring
    - ceph
