---

- hosts: compute
  become: yes
  tasks:
    - name: install python
      package:
        name: python3
        state: present
    - name: install firewalld
      package:
        name: firewalld 
        state: present

    - name: disable SELinux
      shell: "sed -i s/^SELINUX=.*$/SELINUX=permissive/ /etc/selinux/config"
    - name: Show SELINUX
      shell: "cat /etc/selinux/config"
      register: command_output

    - debug:
        var: command_output.stdout_lines

- hosts: compute
  become: yes
  roles:
    - citc_user
    - filesystem
    - ssh
    #- security_updates
    - ntp
    - sssd
    - lmod
    - packages
    - mpi
    - slurm
    - monitoring
    - ceph
    - distrac
